DNA = {
    'ictidomys': {
        'TMSB10': 'ATGGCAGACAAGCCGGACATGGGGGAAATCGCCAGCTTCGATAAGGCCAAGCTGAAGAAAACCGAGACGCAGGAGAAGAATACCCTGCCGACCAAAGAGACCATTGAGCAGGAAAAGCGGAGTGAAATTTCCTAA',
        'PLN': 'ATGGAGAAAGTCCAATATCTCACTCGCTCTGCTATAAGAAGAGCCTCAACTATTGAAATGCCTCAACAAGCACGTCAAAATTTCCAGAACCTGTTTATCAATTTCTGTCTCATCTTAATATGTCTCTTGCTGATTTGCATCATCGTGATGCTTCTCTGA',
        'USMG5': 'ATGGCAGGTCCAGAAAATGATGCCCAATTCCAGTTCACTGGTATTAAAAAATATTTCAACTCTTATACTCTCACTGGTAGAATGAATTGTGTACTGGCTACATATGGAGGCATTGCTTTGGCTGTCTTATACTTCAAGCTAAGATCTAAAAAAACTCCAGCTGTGAAAGCAACATAA',
        'MT4': 'ATGGACCCCGGGGATTGCACCTGCATGTCTGGAGGAATGTGCATCTGTGGAGACAACTGCAAATGTACAACTTGCAGCTGCAAAACATGTCGTAAAAGCTGCTGTCCCTGCTGCCCCCCAGGCTGTGCCAAGTGTGCCCGGGGTTGCATCTGCAAAGGGAGCTCGGACAAGTGCAACTGCTGTGCCTGA',
        'GNG13': 'ATGGAGGAGTGGGATGTACCCCAGATGAAGAAGGAGGTCGAGAGCCTCAAGTACCAGCTGGCCTTCAAGAGGGAGATGTCCTCCAAGACCATCCCCGAGCTCCTCAAATGGATCGAGGATGGCATCCCCAAAGACCCCTTCCTGAACCCAGACCTGATGAAGAACAACCCCTGGGTGGAGAAGGGCAAGTGTGCCATCCTGTGA',
    },
    'mus': {
        'TMSB10': 'ATGGCAGACAAGCCGGACATGGGGGAAATCGCCAGCTTCGATAAGGCCAAGCTGAAGAAAACCGAGACGCAGGAGAAGAACACCCTGCCGACCAAAGAGACCATTGAACAGGAAAAGAGGAGTGAAATCTCCTAA',
        'PLN': 'ATGGAAAAAGTGCAATACCTCACTCGCTCGGCTATCAGGAGAGCCTCCACTATTGAAATGCCTCAGCAAGCACGTCAGAATCTCCAGAACCTATTTATCAATTTCTGCCTCATCTTGATATGTCTGCTGCTGATCTGCATCATTGTGATGCTTCTGTGA',
        'USMG5': 'ATGGCTGGTGCAGAAAGTGATGGCCAATTCCAGTTCACTGGTATTAAAAAATATTTCAACTCTTATACCCTCACAGGTAGAATGAATTGTGTCCTGGCCACATATGGAGGCATTGCTTTGCTGGTCTTATACTTCAAGTTAAGGCCTAAGAAAACTCCAGCTGTGAAAGCAACATAA',
        'MT4': 'ATGGACCCTGGGGAATGCACGTGTATGTCTGGAGGGATCTGCATCTGCGGAGATAATTGCAAATGCACAACCTGCAGCTGTAAAACCTGTCGTAAAAGCTGCTGTCCCTGCTGTCCCCCAGGCTGTGCCAAGTGTGCCCGGGGCTGCATCTGCAAAGGGGGTTCAGACAAGTGCAGCTGCTGTCCCTGA',
        'GNG13': 'ATGGAGGAGTGGGATGTGCCCCAGATGAAGAAGGAGGTAGAGAGCCTCAAGTACCAACTGGCCTTCAAGAGGGAGATGTCGTCCAAGACCATCCCCGAGCTTCTCAAGTGGATTGAGGATGGAATCCCCAAGGACCCCTTCCTGAACCCAGACCTGATGAAGAACAACCCTTGGGTAGAGAAGGCCAAGTGCACCATCCTATGA',
    },
    'myotis': {
        'TMSB10': 'ATGGCAGACAAGCCAGACATGGGGGAAGTCGCCAGCTTCGATAAGGCGAAGCTGAAGAAGACGGAGACGCAGGAGAAGAACACCCTGCCGACCAAAGAGACCATTGAGCAGGAGAAGCGGAGTGAG---------',
        'PLN': 'ATGGAGAAAGTCCAATACCTCACTCGCTCTGCTATAAGAAGAGCTTCAACCATTGAAATGCCTCAACAAGCACGTCAAAATCTCCAGAACCTGTTCATCAACTTCTGTCTCATCTTAATATGCCTCTTGCTGATCTGCATCATCGTGATGCTTCTCTGA',
        'USMG5': 'ATGGCAGGTCCAGAAGCTGATGCCCAATTCCAGTTCACTGGTATCAAAAAATATTTCAACTCTTATACTCTCACAGGTAGAATGAATTGTGTAATGGCTACATATGGAAGCATTGCTTTGCTGATTTTATACTTCAAGTTAAGGTCCAAAAAAACTCCAGCTGTGAAAGCAACATGA',
        'MT4': 'ATGGACCCTGGAGAGTGCTCCTGCTTGTCTGGAGGAATATGCATCTGTGGAGACAACTGCAAATGCACAACTTGCAACTGTAAAACATGTCGAAAAAGCTGCTGCGCCTGCTGCCCCCCGGGCTGTGCCAAGTGTGCCCAGGGCTGCATCTGCAAAGGAGGCTCCAGCAAGTGCAGCTGCTGCCCTTGA',
        'GNG13': 'ATGGAGGAGTGGGACGTGCCCCAGATGAAGAAGGAGGTTGAGAGCCTCAAGTACCAGCTGGCCTTCAAAAGGGAGATGTCATCCAAGAGCATCCCTGAGCTCCTCAAGTGGATCGAGGAGGGGATCCCCAAAGACCCCTTCCTGAACCCTGACCTCATGAAGAACAACCCGTGGGTGGAGAAGGGCAAGTGTGCCATCCTGTGA',
    },
    'nomascus': {
        'TMSB10': '---GCAGACAAACCAGACATGGGGGGAATCGCCAGCTTCGATAGGGCCAAGCTGAAGAAAACGGAGACGCAGGAGAAGAACACCCTGCCGACCAAAGAGACCACTGGGCAG---AAGCGGAGTGGAATTTCC---',
        'PLN': 'ATGGAGAAAGTCCAACACCTCACTCGCTCAGCTATAAGAAGAGCCTCAACCATTGAAATGCCTCAACAAGCACGTCAAAATCTACAGAATCTATTTATCAATTTCTGTCTCATCTTAATATGTCTCTTGCTGATCTGTATCATCGTGATGCTTCTCTGA',
        'USMG5': 'ATGGCAGGTCCAGAAAATGATGCGCAATACCAGTTCACTGGTATTAAAAAATATTTCAACTCTTATACTCTCACAGGTAGAATGAACTGTGTACTGGCCACATATGGAAGCATTGCTTTGATTGTCTTATATTTCAAGTTAAGGTCCAAAAAAACTCCAGCTGTGAAAGCAACATAA',
        'MT4': 'ATGGACCCCAGGGAATGTGTCTGCATGTCTGGAGGAATATGCATGTGTGGAGACAACTGCAAATGCACAACCTGCAACTGTAAAACGTGTCGGAAGAGCTGCTGTCCCTGCTGCCCCCCGGGCTGTGCCAAATGTGCCCGGGGCTGCATCTGCAAAGGAGGCTCAGACAAGTGCAGCTGCTGCCCATGA',
        'GNG13': 'ATGGAGGAGTGGGACGTGCCACAGATGAAGAAAGAGGTGGAGAGCCTCAAGTACCAGCTGGCCTTCCAGCGGGAGATGGCATCCAGGACCATCCCCGAGCTGCTGAAGTGGATCGAGGATGGGATTCCCAAGGACCCCTTCCTGAACCCCGACCTGATGAAGAACAACCCATGGGTGGAAAAGGGCAAATGCACCATCCTGTGA',
    },
    'pteropus': {
        'TMSB10': 'ATGGCAGACAAGCCGGACATGGGGGAAATCGCCAGCTTTGATAAGGCCAAGCTGAAGAAGACGGAGACGCAGGAGAAGAACACCCTGCCGACCAAAGAGACCATTGAG---GAGAAGCAGAGTGAAATTTCCTAA',
        'PLN': 'ATGGAGAAAGTCCAATACCTCACTCGCTCTGCTATAAGAAGAGCTTCAAACATTGAAATGCCTCAACAAGCACGTCAGAATCTCCAGAACCTATTTATCAATTTCTGTCTCATCTTAATATGTCTCTTGTTGATCTGCATCATCGTGATGCTTCTCTGA',
        'USMG5': 'ATGGCAGGTCCAGAAGCTGATGCCCAGTTCCATTTCACTGGCATTAAGAAATATTTCAACTCTTATACGATCACAGGTAGAATGAATTGTGTACTGGCCACATATGGAGGCCTTGCTTTGGCTTGTTTATACTTCAAGTTAAGATCT---AAAACTCCAGCTGTGAAAGCA------',
        'MT4': 'ATGGACCCCAGGGAATGCTCCTGCATGTCTGGAGGAATCTGCATCTGTGGAGACGACTGCAAATGCACAACTTGCAACTGTAAAACATGTCGAAAAAGCTGCTGCTCCTGCTGCCCCCCAGGCTGTGCCAAGTGCGCCCGAGGCTGCATCTGCAAAGGGGGCTCAAACAAGTGCAGCTGCTGCCACTGA',
        'GNG13': 'ATGGAGGAATGGGACGTGCCCCAGATGAAGAAAGAAGTTGAGAGCCTCAAGTACCAGCTGGCCTTCAAGAGGGAGATGTCATCCAAGACCATCCCTGAGCTTCTCAAATGGATCGAGGATGGGATCCCCAAGGACCCCTTCCTGAACCCTGACCTGATGAAGAACAACCCATGGGTAGAGAAGGGCAAGTGCTCCATCCTGTGA',
    }
}